import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import java.io.InputStream;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.player.*;

public class Audio_Section extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
String genre="";
FileInputStream FIS;
BufferedInputStream BIS;
Player player;
File file=null;
long len;
long pouse;
String lan="";
String value="",value1="";
    /**
     * Creates new form Audio_Section
     */
    public Audio_Section() {
        initComponents();
        conn=Connector.Connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        hindi = new javax.swing.JCheckBox();
        bengali = new javax.swing.JCheckBox();
        english = new javax.swing.JCheckBox();
        othes = new javax.swing.JCheckBox();
        assam = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        playname = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setTitle("Audio Player");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select The Language", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        buttonGroup1.add(hindi);
        hindi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hindi.setForeground(new java.awt.Color(255, 255, 255));
        hindi.setText("Hindi");
        hindi.setOpaque(false);
        hindi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hindiActionPerformed(evt);
            }
        });

        buttonGroup1.add(bengali);
        bengali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bengali.setForeground(new java.awt.Color(255, 255, 255));
        bengali.setText("Bengali");
        bengali.setOpaque(false);
        bengali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bengaliActionPerformed(evt);
            }
        });

        buttonGroup1.add(english);
        english.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        english.setForeground(new java.awt.Color(255, 255, 255));
        english.setText("English");
        english.setOpaque(false);
        english.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishActionPerformed(evt);
            }
        });

        buttonGroup1.add(othes);
        othes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        othes.setForeground(new java.awt.Color(255, 255, 255));
        othes.setText("Others");
        othes.setOpaque(false);
        othes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othesActionPerformed(evt);
            }
        });

        buttonGroup1.add(assam);
        assam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        assam.setForeground(new java.awt.Color(255, 255, 255));
        assam.setText("Assamese");
        assam.setOpaque(false);
        assam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(hindi)
                .addGap(18, 18, 18)
                .addComponent(bengali)
                .addGap(18, 18, 18)
                .addComponent(english)
                .addGap(18, 18, 18)
                .addComponent(assam)
                .addGap(18, 18, 18)
                .addComponent(othes)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hindi)
                    .addComponent(bengali)
                    .addComponent(english)
                    .addComponent(othes)
                    .addComponent(assam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 130, 700, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select The Mood", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Happy.png"))); // NOI18N
        jLabel3.setToolTipText("Happiness");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sad.png"))); // NOI18N
        jLabel7.setToolTipText("Joy");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Party.png"))); // NOI18N
        jLabel4.setToolTipText("Sadness");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Romantic.png"))); // NOI18N
        jLabel5.setToolTipText("Upset");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Angry.png"))); // NOI18N
        jLabel6.setToolTipText("Angry");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(66, 66, 66)
                .addComponent(jLabel7)
                .addGap(79, 79, 79)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 200, 690, 120);

        jScrollPane1.setOpaque(false);

        table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Genre", "FileName", "AudioFile"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setOpaque(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 690, 150);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Audio Player", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        playname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playname.setForeground(new java.awt.Color(255, 255, 255));
        playname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playname.setText("...................");

        jButton7.setBackground(new java.awt.Color(255, 255, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_001_-_play_2949803.png"))); // NOI18N
        jButton7.setText("Start Player");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_004_-_Pause_2949806.png"))); // NOI18N
        jButton8.setText("Pause Player");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton8MouseReleased(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_017_-_Reload_2949819.png"))); // NOI18N
        jButton9.setText("Resume Player");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton9MouseReleased(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 102));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_008_-_Record_2949810.png"))); // NOI18N
        jButton10.setText("Stop Player");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton10MouseReleased(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 190, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(playname, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(playname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, -2, 710, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 720, 510);

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Display Genre List");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(20, 260, 115, 37);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 713, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        InputStream in;
        String str=playname.getText();
        //str=str.replaceAll("(?=[]\\[+&|!(){}^\"~*?\\\\-])", "\\\\");
            str=str.replaceAll("\\\\", "\\\\\\\\");
                playname.setText(str);
                try{
                    file=new File(str);
                    FIS=new FileInputStream(file);
                    BIS=new BufferedInputStream(FIS);
                    player=new Player(BIS);
                    len=FIS.available();
                    new Thread()
                    {
                        public void run()
                        {
                            try{
                                player.play();
                            }catch(Exception ex){
                                System.out.println(ex);
                            }
                        }
                    }.start();
                }catch(Exception ex){
                    System.out.println(ex);
                }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseReleased
        if(player!=null){
            try{
                pouse=FIS.available();
                player.close();
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jButton8MouseReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseReleased
        try{
            FIS=new FileInputStream(file);
            BIS=new BufferedInputStream(FIS);
            player=new Player(BIS);
            FIS.skip(len-pouse);
            new Thread()
            {
                public void run()
                {
                    try{
                        player.play();
                    } catch(Exception ex){
                        System.out.println(ex);
                    }
                }
            }.start();
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton9MouseReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseReleased
        if(player!=null){
            player.close();
            playname.setText("...........");
        }
    }//GEN-LAST:event_jButton10MouseReleased

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        if(player!=null){
            player.close();
            playname.setText("...........");
        }
        int column = 3;
        int row = table.getSelectedRow();
        value = table.getModel().getValueAt(row, column).toString();
        column=1;
        value1 = table.getModel().getValueAt(row, column).toString();
        //String sql="select * from music_box where Filename"
        playname.setText(""+value);
        JOptionPane.showMessageDialog(this,"Your Selected File Is:"+value1);
    }//GEN-LAST:event_tableMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        genre="Happiness";
        
        if(genre.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Select Your Genre Of Song");
        }
        else{
            String sql="select * from music_box where Genre='"+genre+"'";
            try
            {
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if(player!=null){
            player.close();
            playname.setText("...........");
        }
        this.hide();
        new Index_Page().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        genre="Happiness";
        if(player!=null){
            player.close();
            playname.setText("...........");
        }
        if(genre.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Select Your Genre Of Song");
        }
        else{
            String sql="select * from music_box where Genre='"+genre+"' and Language='"+lan+"'";
            try
            {
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception ex){
                System.out.println(ex);
            }
        }

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        genre="Party";
        if(player!=null){
            player.close();
            playname.setText("...........");
        }
        if(genre.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Select Your Genre Of Song");
        }
        else{
            String sql="select * from music_box where Genre='"+genre+"' and Language='"+lan+"'";
            try
            {
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        genre="Romantic";
        if(player!=null){
            player.close();
            playname.setText("...........");
        }if(genre.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Select Your Genre Of Song");
        }
        else{
            String sql="select * from music_box where Genre='"+genre+"' and Language='"+lan+"'";
            try
            {
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        genre="Angry";
        if(player!=null){
            player.close();
            playname.setText("...........");
        }
        if(genre.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Select Your Genre Of Song");
        }
        else{
            String sql="select * from music_box where Genre='"+genre+"'";
            try
            {
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        genre="Sadness";
        if(player!=null){
            player.close();
            playname.setText("...........");
        }
        if(genre.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Select Your Genre Of Song");
        }
        else{
            String sql="select * from music_box where Genre='"+genre+"' and Language='"+lan+"'";
            try
            {
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void hindiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hindiActionPerformed
        // TODO add your handling code here:
        if(hindi.isSelected()==true)
            lan="Hindi";
        //JOptionPane.showMessageDialog(this,"You Choose:"+lan);
    }//GEN-LAST:event_hindiActionPerformed

    private void bengaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bengaliActionPerformed
        // TODO add your handling code here:
         if(bengali.isSelected()==true)
            lan="Bengali";
    }//GEN-LAST:event_bengaliActionPerformed

    private void englishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishActionPerformed
        // TODO add your handling code here:
         if(english.isSelected()==true)
            lan="English";
    }//GEN-LAST:event_englishActionPerformed

    private void assamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assamActionPerformed
        // TODO add your handling code here:
         if(assam.isSelected()==true)
            lan="Assamese";
    }//GEN-LAST:event_assamActionPerformed

    private void othesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othesActionPerformed
        // TODO add your handling code here:
         if(othes.isSelected()==true)
            lan="Others";
    }//GEN-LAST:event_othesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Audio_Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Audio_Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Audio_Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Audio_Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Audio_Section().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox assam;
    private javax.swing.JCheckBox bengali;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox english;
    private javax.swing.JCheckBox hindi;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox othes;
    private javax.swing.JLabel playname;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
